[package]
name = "raven_import_demo"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raven_core = { path="../raven_core" }
image = "0.23.14"
