[package]
name = "raven_ecs_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raven_ecs = { path="../raven_ecs" }
serde = { version = "1.0.127", features = ["derive"] }
